---

- name: Ubuntu developer tools
  include_role:
    name: "{{ galaxy_role }}"
    apply:
      become: yes
  loop:
    - geerlingguy.nodejs
    - geerlingguy.docker
    - huxoll.azure-cli
    - ngetchell.vscode
    - andrewrothstein.terraform
    - pixelart.chrome
  loop_control:
    loop_var: galaxy_role
  vars:
    - nodejs_version: "10.x"

- name: Add 'docker' group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
