---

- name: Ubuntu developer tools
  include_role:
    name: "{{ galaxy_role }}"
  loop:
    - geerlingguy.nodejs
    - geerlingguy.docker
    - huxoll.azure-cli
    - ngetchell.vscode
    - andrewrothstein.terraform
    - pixelart.chrome
  loop_control:
    loop_var: galaxy_role
  vars:
    - ansible_become: yes
    - nodejs_version: "10.x"

