---
kind: pipeline
type: docker
name: build
  
steps:
- name: Build Ubuntu
  image: ubuntu:18.04
  commands:
  - cd ./ubuntu
  - ./setupansible.sh
  - ansible-lint ../ubuntu/playbook.yml
  - ansible-lint ../windows/playbook.yml  
  - ./runplaybook.sh -e