---
kind: pipeline
type: docker
name: build
  
steps:
- name: Build
  image: ubuntu:18.04
  commands:
  - ./scripts/setup-debian.sh
  - ansible-lint ./developer.yml
  - ansible-galaxy install -r ./requirements.yml
  - ansible-playbook developer.yml -i localhost --extra-vars="pubkey='ssh-rsa PubKey'"
