---

- name: Install Ubuntu desktop and xrdp
  become: yes
  apt:
    pkg:
      - ubuntu-desktop
      - xrdp
    state: present
    update_cache: yes

- name: Allow xrdp to listen on port 443
  become: yes
  capabilities:
    path: /usr/sbin/xrdp
    capability: cap_net_bind_service+eip
    state: present

- name: Update xrdp config to listen on port 443
  become: yes
  replace:
    path: /etc/xrdp/xrdp.ini
    regexp: '^port=[0-9]+$'
    replace: 'port=443'

- name: Enable xrdp service on boot
  become: yes
  service:
    name: xrdp
    state: restarted
    enabled: yes

