---

- name: Install Ubuntu desktop and xrdp
  apt:
    name: '{{ item }}'
    state: present
  loop:
  - ubuntu-desktop
  - xrdp

- name: Allow xrdp to listen on port 443
  become: yes
  command: setcap CAP_NET_BIND_SERVICE=+eip /usr/sbin/xrdp

- name: Update xrdp config to listen on port 443
  become: yes
  replace:
    path: /etc/xrdp/xrdp.ini
    regexp: '^port=[0-9]+$'
    replace: 'port=443'

- name: Enable xrdp service on boot
  service:
    name: xrdp
    state: restarted
    enabled: yes

